version: "1"
rules:                      # Array of rules
  - base: centos            # Required. Target branch
    upstream: aws:master    # Required. Must be in the same fork network.
    mergeMethod: rebase     # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
